### ISSUE TITLE
Adding Authors to a Pattern Candidate does not work in while Adding it

### ISSUE THREAD

**Issue by lharzenetter** [PatternAtlas/pattern-atlas-ui#125] opened 2021-10-29 14:15 UTC
**Describe the bug**
When creating a new Pattern Candidate, adding another author does not work. 

**To Reproduce**
1. Go to Pattern Cadidates
2. Click on Add New
3. Try to add another user as an author

**Expected behavior**
I can add the user as an author.

**Found by**: @mar-be

**Comment by mhinkie** [comment] 2022-04-05 13:27
UI attempts PUT on http://localhost:1977/patternatlas/issues/undefined/authors since the issue is not yet created. Will change UI for Issues and Candidate to defer setting autors until the save button is clicked

**Comment by mhinkie** [comment] 2022-04-05 15:17
Fixed in `ba-meyer-master` (see c64b71c)

**Closed** 2022-11-24 12:34 UTC
Labels: bug
